/*
 * LDA Parameters for RA8E1 Inference
 * Auto-generated by MATLAB
 * Date: 27-Jan-2026 12:33:05
 */

#ifndef LDA_PARAMS_H
#define LDA_PARAMS_H

#define LDA_NUM_FEATURES 25
#define LDA_NUM_CLASSES 4

/* Class definitions */
#define CLASS_CLASS0 0
#define CLASS_CLASS1 1
#define CLASS_CLASS2 2
#define CLASS_CLASS3 3

/* Weight matrix W [25 x 4] (column-major) */
static const float lda_weights[LDA_NUM_FEATURES * LDA_NUM_CLASSES] = {
    /* Class 0 (class0) */
    -22.3475777869f,
    5.3021417299f,
    31.9426902830f,
    -25.9287267727f,
    -7.4817242584f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    /* Class 1 (class1) */
    6.2044735573f,
    -9.3979445441f,
    -17.1085759830f,
    -4.1417392363f,
    22.4885662092f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    /* Class 2 (class2) */
    15.5437371508f,
    0.3521970975f,
    -18.4710496831f,
    12.7133448011f,
    0.7065733497f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    /* Class 3 (class3) */
    14.1877238745f,
    1.6854023937f,
    -14.4375981717f,
    38.1214936339f,
    -15.9384053356f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f
};

/* Bias vector b [4] */
static const float lda_bias[LDA_NUM_CLASSES] = {
    -13.3672648966f,  /* class0 */
    -5.5525357143f,  /* class1 */
    -6.0105232222f,  /* class2 */
    -21.7363089858f  /* class3 */
};

/* LDA Inference function prototype */
/*
 * Input:  features[LDA_NUM_FEATURES] - HLAC feature vector
 * Output: Predicted class ID (0 to 3)
 *
 * Example implementation:
 *   int lda_predict(const float *features) {
 *       float scores[LDA_NUM_CLASSES];
 *       
 *       // Compute scores = W^T * features + b
 *       for (int c = 0; c < LDA_NUM_CLASSES; c++) {
 *           scores[c] = lda_bias[c];
 *           for (int f = 0; f < LDA_NUM_FEATURES; f++) {
 *               scores[c] += lda_weights[c * LDA_NUM_FEATURES + f] * features[f];
 *           }
 *       }
 *       
 *       // Find argmax
 *       int max_class = 0;
 *       float max_score = scores[0];
 *       for (int c = 1; c < LDA_NUM_CLASSES; c++) {
 *           if (scores[c] > max_score) {
 *               max_score = scores[c];
 *               max_class = c;
 *           }
 *       }
 *       
 *       return max_class;
 *   }
 */

#endif /* LDA_PARAMS_H */
