/*
 * LDA Parameters for RA8E1 Inference
 * Auto-generated by MATLAB
 * Date: 15-Mar-2026 23:44:42
 */

#ifndef LDA_PARAMS_H
#define LDA_PARAMS_H

#define LDA_NUM_FEATURES 25
#define LDA_NUM_CLASSES 4

/* Class definitions */
#define CLASS_CLASS0 0
#define CLASS_CLASS1 1
#define CLASS_CLASS2 2
#define CLASS_CLASS3 3

/* Weight matrix W [25 x 4] (column-major) */
static const float lda_weights[LDA_NUM_FEATURES * LDA_NUM_CLASSES] = {
    /* Class 0 (class0) */
    -25.2608663106f,
    9.0121617103f,
    23.3879020377f,
    -19.3530570675f,
    4.8344462909f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    /* Class 1 (class1) */
    -6.1341271245f,
    -1.8229109160f,
    5.5754468325f,
    -9.7226516677f,
    10.4830463424f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    /* Class 2 (class2) */
    4.2225214115f,
    -0.3888447207f,
    -2.7183035331f,
    3.8482505823f,
    -3.9870844678f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    /* Class 3 (class3) */
    6.2060491004f,
    -0.9279253231f,
    -7.2390728975f,
    7.3978666690f,
    -3.4036660358f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f
};

/* Bias vector b [4] */
static const float lda_bias[LDA_NUM_CLASSES] = {
    -18.5903717857f,  /* class0 */
    -2.8616626512f,  /* class1 */
    -1.2818361505f,  /* class2 */
    -2.3861451091f  /* class3 */
};

/* LDA Inference function prototype */
/*
 * Input:  features[LDA_NUM_FEATURES] - HLAC feature vector
 * Output: Predicted class ID (0 to 3)
 *
 * Example implementation:
 *   int lda_predict(const float *features) {
 *       float scores[LDA_NUM_CLASSES];
 *       
 *       // Compute scores = W^T * features + b
 *       for (int c = 0; c < LDA_NUM_CLASSES; c++) {
 *           scores[c] = lda_bias[c];
 *           for (int f = 0; f < LDA_NUM_FEATURES; f++) {
 *               scores[c] += lda_weights[c * LDA_NUM_FEATURES + f] * features[f];
 *           }
 *       }
 *       
 *       // Find argmax
 *       int max_class = 0;
 *       float max_score = scores[0];
 *       for (int c = 1; c < LDA_NUM_CLASSES; c++) {
 *           if (scores[c] > max_score) {
 *               max_score = scores[c];
 *               max_class = c;
 *           }
 *       }
 *       
 *       return max_class;
 *   }
 */

#endif /* LDA_PARAMS_H */
