/*
 * LDA Parameters for RA8E1 Inference
 * Auto-generated by MATLAB
 * Date: 12-Feb-2026 14:31:31
 */

#ifndef LDA_PARAMS_H
#define LDA_PARAMS_H

#define LDA_NUM_FEATURES 25
#define LDA_NUM_CLASSES 3

/* Class definitions */
#define CLASS_CLASS0 0
#define CLASS_CLASS1 1
#define CLASS_CLASS2 2

/* Weight matrix W [25 x 3] (column-major) */
static const float lda_weights[LDA_NUM_FEATURES * LDA_NUM_CLASSES] = {
    /* Class 0 (class0) */
    -3.4352352810f,
    -2.8004169046f,
    18.7595707847f,
    -6.5401565841f,
    -7.3561604502f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    /* Class 1 (class1) */
    -4.9938138932f,
    3.2003097423f,
    -10.5136506395f,
    3.7709609923f,
    7.5854198704f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    /* Class 2 (class2) */
    13.9657152531f,
    0.7203517269f,
    -20.8484825791f,
    7.1135599405f,
    3.0966277271f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f
};

/* Bias vector b [3] */
static const float lda_bias[LDA_NUM_CLASSES] = {
    -2.2242878340f,  /* class0 */
    -2.5393819881f,  /* class1 */
    -6.3178448609f  /* class2 */
};

/* LDA Inference function prototype */
/*
 * Input:  features[LDA_NUM_FEATURES] - HLAC feature vector
 * Output: Predicted class ID (0 to 2)
 *
 * Example implementation:
 *   int lda_predict(const float *features) {
 *       float scores[LDA_NUM_CLASSES];
 *       
 *       // Compute scores = W^T * features + b
 *       for (int c = 0; c < LDA_NUM_CLASSES; c++) {
 *           scores[c] = lda_bias[c];
 *           for (int f = 0; f < LDA_NUM_FEATURES; f++) {
 *               scores[c] += lda_weights[c * LDA_NUM_FEATURES + f] * features[f];
 *           }
 *       }
 *       
 *       // Find argmax
 *       int max_class = 0;
 *       float max_score = scores[0];
 *       for (int c = 1; c < LDA_NUM_CLASSES; c++) {
 *           if (scores[c] > max_score) {
 *               max_score = scores[c];
 *               max_class = c;
 *           }
 *       }
 *       
 *       return max_class;
 *   }
 */

#endif /* LDA_PARAMS_H */
