/*
 * LDA Parameters for RA8E1 Inference
 * Auto-generated by MATLAB
 * Date: 18-Jan-2026 14:00:21
 */

#ifndef LDA_PARAMS_H
#define LDA_PARAMS_H

#define LDA_NUM_FEATURES 25
#define LDA_NUM_CLASSES 4

/* Class definitions */
#define CLASS_CLASS0 0
#define CLASS_CLASS1 1
#define CLASS_CLASS2 2
#define CLASS_CLASS3 3

/* Weight matrix W [25 x 4] (column-major) */
static const float lda_weights[LDA_NUM_FEATURES * LDA_NUM_CLASSES] = {
    /* Class 0 (class0) */
    -88.0935984055f,
    46.6871628310f,
    46.7973061235f,
    -13.2554785014f,
    -36.9286585836f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    /* Class 1 (class1) */
    -8.9842831876f,
    10.9290260587f,
    3.5403678434f,
    -5.5693242878f,
    -12.4622745396f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    /* Class 2 (class2) */
    5.1492755024f,
    -1.7559913104f,
    -0.8169948507f,
    3.9671543928f,
    -9.5019552743f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    /* Class 3 (class3) */
    89.1739154917f,
    -53.7971963394f,
    -48.7814851812f,
    12.9285579573f,
    59.8274078274f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f,
    0.0000000000f
};

/* Bias vector b [4] */
static const float lda_bias[LDA_NUM_CLASSES] = {
    -30.2378273458f,  /* class0 */
    -4.2627724031f,  /* class1 */
    -1.9812391506f,  /* class2 */
    -48.6912112397f  /* class3 */
};

/* LDA Inference function prototype */
/*
 * Input:  features[LDA_NUM_FEATURES] - HLAC feature vector
 * Output: Predicted class ID (0 to 3)
 *
 * Example implementation:
 *   int lda_predict(const float *features) {
 *       float scores[LDA_NUM_CLASSES];
 *       
 *       // Compute scores = W^T * features + b
 *       for (int c = 0; c < LDA_NUM_CLASSES; c++) {
 *           scores[c] = lda_bias[c];
 *           for (int f = 0; f < LDA_NUM_FEATURES; f++) {
 *               scores[c] += lda_weights[c * LDA_NUM_FEATURES + f] * features[f];
 *           }
 *       }
 *       
 *       // Find argmax
 *       int max_class = 0;
 *       float max_score = scores[0];
 *       for (int c = 1; c < LDA_NUM_CLASSES; c++) {
 *           if (scores[c] > max_score) {
 *               max_score = scores[c];
 *               max_class = c;
 *           }
 *       }
 *       
 *       return max_class;
 *   }
 */

#endif /* LDA_PARAMS_H */
